### ISSUE TITLE
Path and filename too long

### ISSUE THREAD

**Issue by boegh** [flickr-downloadr/flickr-downloadr#15]
Now that I've found the log, I can contribute a bit more :)

I get the following error when trying to download. Unfortunately parts of it, is in Danish - probably since my Windows installation is in Danish. I do believe however, that the key message is the one I have marked with bold, and it translates to something like:

The provided path and/or the provided filename is too long. The fully qualified name must be less than 260 characters, and the folders name must be less than 248 characters. 

Den angivne sti og/eller det angivne filnavn er for langt. Det fuldt kvalificerede navn skal være på mindre end 260 tegn, og mappenavnet skal være på mindre end 248 tegn. The folder name I have used was something like (65 characters by my count):

C:\Users\heb\Desktop\flickr\flickr-downloadr-2013-04-04_14-34-10

So I'm guessing the issue is with the filename being too long.

The line 'Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløs' translates to 'The end of the stacktrace from the previous location, where the exception was triggered' and is also in there a few times.

<log4j:event logger="FloydPink.Flickr.Downloadr.UI.App" timestamp="1365078876612" level="INFO" thread="1"><log4j:message>Application Start.</log4j:message><log4j:properties><log4j:data name="log4net:UserName" value="heb-Pc\heb" /><log4j:data name="log4jmachinename" value="heb-Pc" /><log4j:data name="log4japp" value="DefaultDomain" /><log4j:data name="log4net:HostName" value="heb-Pc" /></log4j:properties><log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.App" method="OnStartup" file="" line="0" /></log4j:event>
<log4j:event logger="FloydPink.Flickr.Downloadr.UI.App" timestamp="1365078945055" level="INFO" thread="1"><log4j:message>Application Exit.</log4j:message><log4j:properties><log4j:data name="log4net:UserName" value="heb-Pc\heb" /><log4j:data name="log4jmachinename" value="heb-Pc" /><log4j:data name="log4japp" value="DefaultDomain" /><log4j:data name="log4net:HostName" value="heb-Pc" /></log4j:properties><log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.App" method="OnExit" file="" line="0" /></log4j:event>
<log4j:event logger="FloydPink.Flickr.Downloadr.UI.App" timestamp="1365078966430" level="FATAL" thread="1"><log4j:message>Unhandled Exception.</log4j:message><log4j:properties><log4j:data name="log4net:UserName" value="heb-Pc\heb" /><log4j:data name="log4jmachinename" value="heb-Pc" /><log4j:data name="log4japp" value="DefaultDomain" /><log4j:data name="log4net:HostName" value="heb-Pc" /></log4j:properties><log4j:throwable>**<![CDATA[System.IO.PathTooLongException: Den angivne sti og/eller det angivne filnavn er for langt. Det fuldt kvalificerede navn skal være på mindre end 260 tegn, og mappenavnet skal være på mindre end 248 tegn.**
   ved System.IO.PathHelper.GetFullPathName()
   ved System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   ved System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   ved System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   ved System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   ved System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   ved System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   ved System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   ved FloydPink.Flickr.Downloadr.Logic.DownloadLogic.WriteMetaDataFile(Photo photo, String targetFileName, Preferences preferences)
   ved FloydPink.Flickr.Downloadr.Logic.DownloadLogic.<DownloadPhotos>d__4.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved FloydPink.Flickr.Downloadr.Logic.DownloadLogic.<Download>d__0.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved FloydPink.Flickr.Downloadr.Logic.BrowserLogic.<Download>d__a.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved FloydPink.Flickr.Downloadr.Presentation.BrowserPresenter.<DownloadPhotos>d__1e.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved FloydPink.Flickr.Downloadr.Presentation.BrowserPresenter.<DownloadThisPage>d__10.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved FloydPink.Flickr.Downloadr.UI.BrowserWindow.<DownloadThisPageButtonClick>d__26.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ved MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)]]></log4j:throwable><log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.App" method="OnDispatcherUnhandledException" file="" line="0" /></log4j:event>
<log4j:event logger="FloydPink.Flickr.Downloadr.UI.App" timestamp="1365078976562" level="INFO" thread="1"><log4j:message>Application Exit.</log4j:message><log4j:properties><log4j:data name="log4net:UserName" value="heb-Pc\heb" /><log4j:data name="log4jmachinename" value="heb-Pc" /><log4j:data name="log4japp" value="DefaultDomain" /><log4j:data name="log4net:HostName" value="heb-Pc" /></log4j:properties><log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.App" method="OnExit" file="" line="0" /></log4j:event>

**Comment by Katrina--** [comment]
The limit for file names are 256. You can try to fix this with Long Path Tool.
